import json

def cell_md(source): return {"cell_type":"markdown","metadata":{},"source":source}
def cell_code(source): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":source}

cells = [

cell_md([
"# Estratégia 5 — Multi-Camada: Combinando as 4 Estratégias\n",
"**Competição de Carteira de Investimentos 2026 — PPGOLD/UFPR**\n\n",
"---\n",
"## Arquitetura da Estratégia\n\n",
"Nenhuma estratégia individual captura toda a realidade do mercado. Esta abordagem funde os melhores elementos de cada metodologia em 5 camadas sequenciais e complementares:\n\n",
"```\n",
"┌─────────────────────────────────────────────────────────────────┐\n",
"│  CAMADA 1 — QUALIDADE (Piotroski F-Score)                       │\n",
"│  Filtra empresas fundamentalmente saudáveis (F-Score ≥ 6)       │\n",
"│  Garantia: ROE+, Margem+, Dívida controlada, Eficiência         │\n",
"├─────────────────────────────────────────────────────────────────┤\n",
"│  CAMADA 2 — VALUATION + RENTABILIDADE (EV/EBITDA + FF5)        │\n",
"│  Score Composto: EV/EBITDA + HML (B/M) + RMW (ROE) + CMA      │\n",
"│  Identifica: bem-precificadas E lucrativas                      │\n",
"├─────────────────────────────────────────────────────────────────┤\n",
"│  CAMADA 3 — TIMING: MOMENTUM (12-1)                            │\n",
"│  Confirma tendência de alta — evita value traps                 │\n",
"│  Penaliza: ativos ainda em queda mesmo sendo baratos            │\n",
"├─────────────────────────────────────────────────────────────────┤\n",
"│  CAMADA 4 — DIVERSIFICAÇÃO (Deduplicação por Empresa/Setor)    │\n",
"│  Uma empresa = um ativo: elimina ON+PN da mesma empresa        │\n",
"│  Impõe descorrelação real entre os 4 ativos finais             │\n",
"├─────────────────────────────────────────────────────────────────┤\n",
"│  CAMADA 5 — PONDERAÇÃO ÓTIMA (Markowitz + Combinatória)        │\n",
"│  C(top12, 4) = combinações → Maior Índice de Sharpe absoluto   │\n",
"│  Resultado: Exatamente 4 ativos de empresas distintas          │\n",
"└─────────────────────────────────────────────────────────────────┘\n",
"```\n\n",
"### Por que esta ordem?\n\n",
"| Camada | Pergunta respondida |\n",
"|---|---|\n",
"| Qualidade | *A empresa é confiável para investir?* |\n",
"| Valuation | *O preço está razoável vs. geração de caixa?* |\n",
"| Momentum | *O mercado já reconheceu o valor? É hora de entrar?* |\n",
"| Markowitz | *Qual combinação de 4 e quais pesos maximizam o Sharpe?* |\n",
]),

cell_md(["---\n## Etapa 1 — Importação de Bibliotecas"]),
cell_code([
"import requests, io, warnings\n",
"import pandas as pd\n",
"import numpy as np\n",
"import yfinance as yf\n",
"from itertools import combinations\n",
"from scipy.optimize import minimize\n",
"import matplotlib.pyplot as plt\n",
"import matplotlib.gridspec as gridspec\n",
"import seaborn as sns\n",
"warnings.filterwarnings('ignore')\n",
"sns.set_style('whitegrid')\n",
"print('Bibliotecas carregadas com sucesso.')",
]),

cell_md(["---\n## Etapa 2 — Coleta do Universo B3 (Fundamentus)"]),
cell_code([
"headers = {'User-Agent': 'Mozilla/5.0'}\n",
"df_b3 = pd.read_html(io.StringIO(\n",
"    requests.get('https://www.fundamentus.com.br/resultado.php', headers=headers).text\n",
"), decimal=',', thousands='.')[0]\n",
"\n",
"def pct(s):\n",
"    return pd.to_numeric(s.astype(str).str.replace('.','',regex=False)\n",
"        .str.replace(',','.',regex=False).str.replace('%','',regex=False),\n",
"        errors='coerce') / 100.0\n",
"\n",
"for col in ['ROE','ROIC','Mrg Ebit','Mrg. Líq.','Cresc. Rec.5a','Div.Yield']:\n",
"    df_b3[col] = pct(df_b3[col])\n",
"for col in ['P/L','P/VP','EV/EBITDA','Liq.2meses','Liq. Corr.','Dív.Brut/ Patrim.']:\n",
"    df_b3[col] = pd.to_numeric(df_b3[col], errors='coerce')\n",
"\n",
"print(f'Universo total de ativos na B3: {len(df_b3)}')",
]),

cell_md(["---\n## CAMADA 1 — Piotroski F-Score: Filtro de Qualidade\n\n",
"A primeira camada elimina empresas fundamentalmente frágeis antes de qualquer análise de preço. ",
"Apenas empresas com F-Score ≥ 6 (de 9 possíveis) passam para a próxima etapa.\n"]),
cell_code([
"# Filtro base: liquidez mínima (regra do edital)\n",
"df = df_b3[df_b3['Liq.2meses'] > 5_000_000].copy().reset_index(drop=True)\n",
"\n",
"# Cálculo do F-Score (9 critérios binários)\n",
"df['F1'] = (df['ROE']        > 0  ).astype(int)\n",
"df['F2'] = (df['Mrg. Líq.'] > 0  ).astype(int)\n",
"df['F3'] = (df['ROIC']       > df['ROE']).astype(int)\n",
"df['F4'] = (df['Mrg Ebit']   > df['Mrg. Líq.']).astype(int)\n",
"df['F5'] = (df['Dív.Brut/ Patrim.'] < 1.0).astype(int)\n",
"df['F6'] = (df['Liq. Corr.'] > 1.0).astype(int)\n",
"df['F7'] = (df['Cresc. Rec.5a'] > 0).astype(int)\n",
"df['F8'] = (df['Mrg Ebit']   > 0  ).astype(int)\n",
"df['F9'] = (df['ROIC']       > 0.10).astype(int)\n",
"df['F_SCORE'] = df[['F1','F2','F3','F4','F5','F6','F7','F8','F9']].sum(axis=1)\n",
"\n",
"# Filtro Camada 1\n",
"df_c1 = df[df['F_SCORE'] >= 6].copy()\n",
"print(f'Camada 1 — Empresas com F-Score ≥ 6: {len(df_c1)} (de {len(df)} líquidas)')",
]),

cell_md(["---\n## CAMADA 2 — Score Composto: Valuation (EV/EBITDA) + Fama-French\n\n",
"Sobre as empresas qualificadas pela Camada 1, calculamos um Score de Valuation ponderado combinando:\n",
"- **EV/EBITDA** (40%): quanto mais barato vs. geração de caixa, melhor\n",
"- **HML/B-to-M** (25%): price-to-book baixo (1/P/VP), proxy do fator Value de Fama-French\n",
"- **RMW/ROE** (25%): rentabilidade sobre patrimônio (fator lucratividade)\n",
"- **CMA** (10%): crescimento conservador de receitas (fator investimento)\n"]),
cell_code([
"# Filtros adicionais de Valuation\n",
"df_c2 = df_c1[\n",
"    (df_c1['EV/EBITDA'] > 1) &\n",
"    (df_c1['EV/EBITDA'] < 25) &\n",
"    (df_c1['P/VP'] > 0)\n",
"].copy()\n",
"\n",
"df_c2['rank_ev']     = df_c2['EV/EBITDA'].rank(ascending=True)        # Menor EV/EBITDA é melhor\n",
"df_c2['rank_bm']     = (1 / df_c2['P/VP']).rank(ascending=False)      # Maior B/M (menor P/VP) melhor\n",
"df_c2['rank_roe']    = df_c2['ROE'].rank(ascending=False)              # Maior ROE melhor\n",
"df_c2['rank_cresc']  = df_c2['Cresc. Rec.5a'].rank(ascending=True)    # Conservador no investimento\n",
"\n",
"df_c2['Score_C2'] = (\n",
"    df_c2['rank_ev']    * 0.40 +\n",
"    df_c2['rank_bm']    * 0.25 +\n",
"    df_c2['rank_roe']   * 0.25 +\n",
"    df_c2['rank_cresc'] * 0.10\n",
")\n",
"\n",
"df_c2 = df_c2.sort_values('Score_C2')\n",
"print(f'Camada 2 — Após filtros de Valuation: {len(df_c2)} candidatos')\n",
"print('\\nTop 20 por Score Composto Camada 2:')\n",
"display(df_c2[['Papel','F_SCORE','EV/EBITDA','P/VP','ROE','Score_C2']].head(20).reset_index(drop=True))",
]),

cell_md(["---\n## CAMADA 3 — Momentum 12-1: Filtro de Timing\n\n",
"Com o universo reduzido ao Top 20 da Camada 2, verificamos o **Momentum de 12 meses** (excluindo o último) para confirmar que o mercado já começou a reconhecer o valor. Evitamos os chamados *value traps*.\n"]),
cell_code([
"tickers_c2 = [t + '.SA' for t in df_c2.head(25)['Papel'].tolist()]\n",
"\n",
"# Preços dos últimos 13 meses\n",
"precos_mom = yf.download(tickers_c2, start='2025-02-01', end='2026-03-26', progress=False)['Close']\n",
"precos_mom = precos_mom.dropna(axis=1, thresh=int(len(precos_mom)*0.7))\n",
"\n",
"# Momentum = retorno dos primeiros 12 meses (excluindo último)\n",
"if len(precos_mom) > 21:\n",
"    preco_ini = precos_mom.iloc[0]\n",
"    preco_fim = precos_mom.iloc[-21]  # 1 mês atrás\n",
"    momentum = (preco_fim / preco_ini - 1).dropna()\n",
"    momentum.name = 'Momentum'\n",
"    df_mom = pd.DataFrame(momentum)\n",
"    df_mom.index = df_mom.index.str.replace('.SA','')\n",
"else:\n",
"    # Fallback: retorno de 6 meses\n",
"    preco_ini = precos_mom.iloc[0]\n",
"    preco_fim = precos_mom.iloc[-1]\n",
"    momentum = (preco_fim / preco_ini - 1).dropna()\n",
"    momentum.name = 'Momentum'\n",
"    df_mom = pd.DataFrame(momentum)\n",
"    df_mom.index = df_mom.index.str.replace('.SA','')\n",
"\n",
"# Merge momentum no score\n",
"df_c2['Momentum'] = df_c2['Papel'].map(df_mom['Momentum'].to_dict())\n",
"df_c2['rank_mom'] = df_c2['Momentum'].rank(ascending=False)\n",
"\n",
"# Score Final com Momentum\n",
"df_c2['Score_Final'] = df_c2['Score_C2'] * 0.65 + df_c2['rank_mom'] * 0.35\n",
"df_final = df_c2.sort_values('Score_Final').dropna(subset=['Momentum'])\n",
"\n",
"print('Top 12 finais — Score Multi-Camada Completo:')\n",
"display(df_final[['Papel','F_SCORE','EV/EBITDA','ROE','Momentum','Score_Final']]\n",
"        .head(12).reset_index(drop=True))",
]),

cell_md([
"---\n## CAMADA 4 — Deduplicação: Uma Empresa = Um Ativo\n\n",
"### O Problema da Falsa Diversificação\n\n",
"Um portfólio contendo PETR**3** e PETR**4** parece ter 4 ativos, mas na prática tem apenas **3 empresas**. ",
"Petrobras ON e PN têm correlação histórica > 0.98 — do ponto de vista quantitativo, é como ter a mesma ação duas vezes.\n\n",
"Isso viola o **princípio central de Markowitz**: a diversificação reduz risco apenas se os ativos forem *descorrelacionados*. ",
"Dois ativos altamente correlacionados não reduzem volatilidade — apenas concentram o risco disfarçado de diversificação.\n\n",
"### A Solução\n\n",
"Para cada empresa identificada pelo **código base do ticker** (ex: `PETR` → agrupa PETR3, PETR4, PETR8), ",
"mantemos apenas o ativo com **melhor Score Final** da Camada 3. O restante é descartado antes da otimização.\n"
]),
cell_code([
"import re\n",
"\n",
"# Extrai o 'código raiz' da empresa (remove sufixo numérico)\n",
"# Ex: 'PETR4' -> 'PETR', 'VALE3' -> 'VALE', 'ITUB4' -> 'ITUB'\n",
"df_final['empresa_base'] = df_final['Papel'].str.replace(r'\\d+$', '', regex=True)\n",
"\n",
"# Para cada empresa, manter apenas o ticker com melhor Score Final (menor valor = melhor)\n",
"df_dedup = (df_final\n",
"    .sort_values('Score_Final')\n",
"    .drop_duplicates(subset='empresa_base', keep='first')\n",
"    .reset_index(drop=True)\n",
")\n",
"\n",
"removidos = set(df_final['Papel']) - set(df_dedup['Papel'])\n",
"if removidos:\n",
"    print(f'⚠️  Ativos removidos por duplicidade de empresa: {removidos}')\n",
"    print('   (Mantido apenas o melhor ticker de cada empresa)')\n",
"else:\n",
"    print('✅  Nenhuma empresa duplicada encontrada no Top 12.')\n",
"\n",
"print(f'\\nCandidatos únicos por empresa: {len(df_dedup)}')\n",
"display(df_dedup[['Papel','empresa_base','F_SCORE','EV/EBITDA','ROE','Momentum','Score_Final']]\n",
"        .head(12).reset_index(drop=True))\n",
"\n",
"# Top 12 final para otimização (após deduplicação)\n",
"top12 = df_dedup.head(12).copy()",
]),

cell_md(["---\n## Visualização: Painel de Métricas do Top 12 (Após Deduplicação)\n\n",
"O painel abaixo exibe os candidatos **já deduplicados por empresa** — máximo um ticker por companhia — prontos para a otimização de Markowitz.\n"]),
cell_code([
"# top12 já foi definido pela célula de deduplicação (df_dedup.head(12))\n",
"# NÃO redefinir aqui — usar a variável deduplicada da Camada 4\n",
"\n",
"fig, axes = plt.subplots(2, 2, figsize=(15, 10))\n",
"fig.suptitle('Top 12 Multi-Camada — Visão Completa das Métricas (empresas únicas)', fontsize=13, fontweight='bold')\n",
"\n",
"# F-Score\n",
"colors_f = ['green' if s >= 7 else 'orange' for s in top12['F_SCORE']]\n",
"axes[0,0].barh(top12['Papel'][::-1], top12['F_SCORE'][::-1], color=colors_f[::-1])\n",
"axes[0,0].set_title('Camada 1: F-Score (Qualidade)')\n",
"axes[0,0].axvline(7, color='red', linestyle='--', alpha=0.5)\n",
"\n",
"# EV/EBITDA\n",
"axes[0,1].barh(top12['Papel'][::-1], top12['EV/EBITDA'][::-1], color='steelblue')\n",
"axes[0,1].set_title('Camada 2: EV/EBITDA (Valuation)')\n",
"\n",
"# ROE\n",
"axes[1,0].barh(top12['Papel'][::-1], top12['ROE'][::-1], color='mediumseagreen')\n",
"axes[1,0].set_title('Camada 2: ROE (Rentabilidade)')\n",
"axes[1,0].xaxis.set_major_formatter(plt.FuncFormatter(lambda x,_: f'{x:.0%}'))\n",
"\n",
"# Momentum\n",
"colors_m = ['seagreen' if m > 0 else 'tomato' for m in top12['Momentum']]\n",
"axes[1,1].barh(top12['Papel'][::-1], top12['Momentum'][::-1], color=colors_m[::-1])\n",
"axes[1,1].set_title('Camada 3: Momentum 12-1 (Timing)')\n",
"axes[1,1].xaxis.set_major_formatter(plt.FuncFormatter(lambda x,_: f'{x:.0%}'))\n",
"axes[1,1].axvline(0, color='gray', linestyle='--', alpha=0.5)\n",
"\n",
"plt.tight_layout()\n",
"plt.show()",
]),

cell_md(["---\n## CAMADA 5 — Otimização Combinatória de Markowitz\n\n",
"Com o universo deduplicado garantindo empresas únicas, testamos **todas as combinações possíveis de 4 ativos**. ",
"Para cada combinação, o otimizador não-linear *SciPy/SLSQP* resolve os pesos que maximizam o **Índice de Sharpe** usando 5 anos de covariância histórica.\n\n",
"### Restrições de Peso (Constraints)\n",
"Para evitar que o otimizador gere carteiras com alocacao **0% em algum ativo** (o que equivale a ter 3 ativos de fato), impomos:\n",
"- **Mínimo por ativo: 5%** — todo ativo contribui de forma real\n",
"- **Máximo por ativo: 80%** — evita concentração excessiva em um único papel\n",
"- **Soma total: 100%** — restrição clássica de Markowitz\n",
"É selecionada apenas a combinação que produz **o maior Índice de Sharpe** com todos os 4 ativos tendo peso efetivo.\n"]),
cell_code([
"tickers_top = [t + '.SA' for t in top12['Papel'].tolist()]\n",
"rf = 0.1075\n",
"\n",
"precos_5a = yf.download(tickers_top, start='2021-03-26', end='2026-03-26', progress=False)['Close']\n",
"precos_5a = precos_5a.dropna(axis=1, thresh=int(len(precos_5a)*0.8)).ffill().dropna()\n",
"tickers_v = precos_5a.columns.tolist()\n",
"\n",
"ret_d = precos_5a.pct_change().dropna()\n",
"mu = ret_d.mean() * 252\n",
"cov = ret_d.cov() * 252\n",
"\n",
"def neg_sharpe(w, mu, cov, rf):\n",
"    r = np.dot(w, mu); v = np.sqrt(w @ cov @ w)\n",
"    return -(r - rf)/v if v > 0 else 0\n",
"\n",
"best_s, best_c, best_w = -np.inf, None, None\n",
"resultados_log = []\n",
"\n",
"# Limites: mínimo 5% e máximo 80% por ativo\n",
"# Isso evita o problema de peso = 0% (ativo fantasma na carteira)\n",
"MIN_PESO, MAX_PESO = 0.05, 0.80\n",
"\n",
"for comb in combinations(tickers_v, 4):\n",
"    mu_c = mu[list(comb)].values\n",
"    cov_c = cov.loc[list(comb), list(comb)].values\n",
"    res = minimize(neg_sharpe, [0.25]*4, args=(mu_c, cov_c, rf),\n",
"                   method='SLSQP', bounds=[(MIN_PESO, MAX_PESO)]*4,\n",
"                   constraints={'type':'eq','fun':lambda w: w.sum()-1})\n",
"    if not res.success:\n",
"        continue\n",
"    w_opt = res.x\n",
"    # Garantia extra: pula combinações onde algum ativo ficou abaixo de 2%\n",
"    if np.any(w_opt < 0.02):\n",
"        continue\n",
"    sh = -res.fun\n",
"    r_opt = np.dot(w_opt, mu_c)\n",
"    v_opt = np.sqrt(w_opt @ cov_c @ w_opt)\n",
"    resultados_log.append({'comb':comb,'sharpe':sh,'ret':r_opt,'vol':v_opt,'pesos':w_opt})\n",
"    if sh > best_s:\n",
"        best_s = sh; best_c = list(comb); best_w = w_opt\n",
"\n",
"mu_f = mu[best_c].values\n",
"cov_f = cov.loc[best_c, best_c].values\n",
"ret_f = np.dot(best_w, mu_f)\n",
"vol_f = np.sqrt(best_w @ cov_f @ best_w)\n",
"\n",
"print('='*60)\n",
"print('CARTEIRA FINAL — ESTRATÉGIA MULTI-CAMADA')\n",
"print('='*60)\n",
"for t, w in zip(best_c, best_w):\n",
"    papel = t.replace('.SA','')\n",
"    mom = df_final[df_final['Papel']==papel]['Momentum'].values\n",
"    ev  = df_final[df_final['Papel']==papel]['EV/EBITDA'].values\n",
"    print(f'  {papel}: {w*100:.2f}%  | EV/EBITDA={ev[0]:.1f}x | Momentum={mom[0]:+.1%}')\n",
"print(f'\\n  Retorno Esperado : {ret_f*100:.2f}% a.a.')\n",
"print(f'  Volatilidade     : {vol_f*100:.2f}% a.a.')\n",
"print(f'  Índice de Sharpe : {best_s:.4f}')\n",
"print(f'  Prêmio vs. CDI   : {(ret_f - rf)*100:.2f}% a.a.')",
]),

cell_md(["---\n## Visualização Final: Fronteira Eficiente + Distribuição de Sharpes"]),
cell_code([
"fig, axes = plt.subplots(1, 2, figsize=(16, 6))\n",
"\n",
"# Fronteira Eficiente (Monte Carlo)\n",
"n_sim = 10000\n",
"rets, vols, sharpes = [], [], []\n",
"for _ in range(n_sim):\n",
"    w = np.random.dirichlet(np.ones(4))\n",
"    r, v = np.dot(w, mu_f), np.sqrt(w @ cov_f @ w)\n",
"    rets.append(r); vols.append(v); sharpes.append((r-rf)/v)\n",
"\n",
"sc = axes[0].scatter(vols, rets, c=sharpes, cmap='viridis', s=8, alpha=0.4)\n",
"fig.colorbar(sc, ax=axes[0], label='Índice de Sharpe')\n",
"axes[0].scatter(vol_f, ret_f, marker='*', color='red', s=300, zorder=5,\n",
"               label=f'Portfólio Ótimo (Sharpe={best_s:.2f})')\n",
"axes[0].axhline(rf, color='gray', linestyle='--', label=f'CDI ({rf*100:.1f}%)')\n",
"axes[0].set_xlabel('Risco (Volatilidade Anual)')\n",
"axes[0].set_ylabel('Retorno Anual')\n",
"axes[0].set_title('Fronteira Eficiente — Carteira Multi-Camada')\n",
"axes[0].legend()\n",
"\n",
"# Alocação por pizza\n",
"labels = [t.replace('.SA','') for t in best_c]\n",
"colors = ['#2196F3','#4CAF50','#FF9800','#E91E63']\n",
"wedges, texts, autotexts = axes[1].pie(\n",
"    best_w, labels=labels, colors=colors, autopct='%1.1f%%',\n",
"    startangle=90, pctdistance=0.85,\n",
"    wedgeprops=dict(width=0.5, edgecolor='white', linewidth=2)\n",
")\n",
"for at in autotexts:\n",
"    at.set_fontsize(11)\n",
"    at.set_fontweight('bold')\n",
"axes[1].set_title('Alocação da Carteira Final (Pesos Ótimos)')\n",
"\n",
"plt.tight_layout()\n",
"plt.show()",
]),

cell_md(["---\n## Indicadores Fundamentalistas para o Relatório Técnico (Edital)"]),
cell_code([
"papeis_f = [t.replace('.SA','') for t in best_c]\n",
"df_ind = df_final[df_final['Papel'].isin(papeis_f)][\n",
"    ['Papel','F_SCORE','ROE','EV/EBITDA','P/VP','Dív.Brut/ Patrim.','Momentum']\n",
"].copy()\n",
"df_ind.columns = ['Ativo','F-Score','ROE (Rentabilidade)','EV/EBITDA (Valuation)','P/VP (Valuation)','Dív/PL (Endividamento)','Momentum 12M']\n",
"df_ind['ROE (Rentabilidade)'] = df_ind['ROE (Rentabilidade)'].map('{:.1%}'.format)\n",
"df_ind['Momentum 12M'] = df_ind['Momentum 12M'].map('{:+.1%}'.format)\n",
"display(df_ind.reset_index(drop=True))\n",
"\n",
"print('\\n==> Esses indicadores atendem DIRETAMENTE as 3 exigências do Edital:')\n",
"print('  ✓ Rentabilidade: ROE')\n",
"print('  ✓ Valuation    : EV/EBITDA + P/VP')\n",
"print('  ✓ Endividamento: Dívida Bruta / PL')",
]),

cell_md(["---\n## Conclusão: Por que esta é a Estratégia Recomendada?\n\n",
"A abordagem Multi-Camada supera cada estratégia individual porque:\n\n",
"1. **Abrangência:** Não depende de um único fator (ex: apenas P/L ou apenas ROE). Avalia qualidade, preço, momentum e risco simultaneamente.\n",
"2. **Cobertura Total:** Varre toda a B3 sem viés humano de seleção.\n",
"3. **Robustez Acadêmica:** Baseia-se em Piotroski (2000), Fama-French (2015), Jegadeesh & Titman (1993) e Markowitz (1952) — quatro pilares consolidados da literatura de finanças, todos alinhados à ementa do PPGOLD.\n",
"4. **Adequação ao Objetivo:** A competição dura meses (curto prazo). O Momentum garante timing correto; o F-Score garante solidez; o EV/EBITDA garante não pagar caro; o Markowitz garante a melhor combinação e alocação possível de exatamente 4 ativos.\n",
])
]

nb = {
 "cells": cells,
 "metadata": {
  "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
  "language_info": {"codemirror_mode": {"name": "ipython", "version": 3},
   "file_extension": ".py", "mimetype": "text/x-python", "name": "python",
   "pygments_lexer": "ipython3", "version": "3.8.0"}
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

out = r"c:\Users\User\Downloads\Competicao-de-Carteiras-2026---Analise-de-Investimento\Estrategia 5 - Combinar 3 Estrategias em Camadas.ipynb"
with open(out, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print(f"Notebook gerado: {out}")
