import json

def cell_md(source): return {"cell_type":"markdown","metadata":{},"source":source}
def cell_code(source): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":source}

cells = [

cell_md([
"# Estratégia 3 — Análise de Momentum (12-1)\n",
"**Competição de Carteira de Investimentos 2026 — PPGOLD/UFPR**\n\n",
"---\n",
"## O que é Momentum?\n\n",
"O efeito Momentum foi documentado por **Jegadeesh & Titman (1993)** e é um dos fenômenos mais consistentes e replicados da literatura de finanças empíricas. A premissa: **ações que performaram melhor nos últimos 12 meses tendem a continuar superando nos próximos 3–12 meses**.\n\n",
"### Por que funciona?\n",
"- Investidores reagem lentamente a boas notícias (*underreaction*) — o preço ajusta gradualmente\n",
"- *Herding behavior*: gestores institucionais compram o que está em alta\n",
"- Revisões sequenciais de resultados: empresas que surpreeendem positivamente tendem a repetir\n\n",
"### Regra de Construção (12-1 Momentum)\n",
"```\n",
"Retorno = Preço hoje / Preço há 12 meses — excluindo o último mês\n",
"         (o último mês é excluído para evitar reversão de curtíssimo prazo)\n",
"```\n\n",
"### Por que é complementar ao Markowitz?\n",
"Markowitz usa covariância *histórica* — o que aconteceu no passado. O Momentum captura *quando entrar*: evita comprar um ativo fundamentalmente barato que ainda está em queda (*value trap*). Combinar Value com Momentum é a base das maiores estratégias quantitativas do mundo (AQR Capital, Renaissance Technologies).\n",
]),

cell_md(["---\n## Etapa 1 — Importação de Bibliotecas"]),
cell_code([
"import requests, io, warnings\n",
"import pandas as pd\n",
"import numpy as np\n",
"import yfinance as yf\n",
"from itertools import combinations\n",
"from scipy.optimize import minimize\n",
"import matplotlib.pyplot as plt\n",
"import seaborn as sns\n",
"from datetime import datetime, timedelta\n",
"warnings.filterwarnings('ignore')\n",
"sns.set_style('whitegrid')\n",
"print('Bibliotecas carregadas.')",
]),

cell_md(["---\n## Etapa 2 — Universo B3 com Filtro de Liquidez"]),
cell_code([
"headers = {'User-Agent': 'Mozilla/5.0'}\n",
"df_b3 = pd.read_html(io.StringIO(\n",
"    requests.get('https://www.fundamentus.com.br/resultado.php', headers=headers).text\n",
"), decimal=',', thousands='.')[0]\n",
"\n",
"df_b3['Liq.2meses'] = pd.to_numeric(df_b3['Liq.2meses'], errors='coerce')\n",
"\n",
"# Filtro de alta liquidez (regra do edital)\n",
"df_liq = df_b3[df_b3['Liq.2meses'] > 5_000_000].copy()\n",
"tickers_b3 = [t + '.SA' for t in df_liq['Papel'].tolist()]\n",
"print(f'Ativos líquidos disponíveis: {len(tickers_b3)}')",
]),

cell_md(["---\n## Etapa 3 — Download de Preços e Cálculo do Momentum 12-1\n\n",
"Baixamos 13 meses de dados históricos e calculamos o retorno acumulado dos últimos 12 meses **excluindo o mês mais recente** (janela de reversão de curto prazo).\n"]),
cell_code([
"# Datas: 13 meses atrás até ontem\n",
"data_fim   = '2026-03-26'\n",
"data_ini   = '2025-02-01'  # 13 meses de dados\n",
"\n",
"# Download em lotes para não sobrecarregar a API\n",
"BATCH = 50\n",
"all_close = []\n",
"for i in range(0, len(tickers_b3), BATCH):\n",
"    lote = tickers_b3[i:i+BATCH]\n",
"    df_tmp = yf.download(lote, start=data_ini, end=data_fim, progress=False)['Close']\n",
"    if isinstance(df_tmp, pd.Series):\n",
"        df_tmp = df_tmp.to_frame()\n",
"    all_close.append(df_tmp)\n",
"\n",
"precos_raw = pd.concat(all_close, axis=1)\n",
"precos_raw = precos_raw.loc[:,~precos_raw.columns.duplicated()]\n",
"\n",
"# Manter apenas colunas com dados suficientes\n",
"precos = precos_raw.dropna(axis=1, thresh=int(len(precos_raw)*0.85))\n",
"print(f'Ativos com histórico suficiente: {precos.shape[1]}')",
]),

cell_code([
"# Cálculo do Momentum 12-1\n",
"# Retorno = preço 'antes do último mês' / preço '13 meses atrás'\n",
"preco_inicial = precos.iloc[0]              # 13 meses atrás\n",
"preco_final   = precos.iloc[-21]            # 1 mês atrás (excluindo último mês)\n",
"\n",
"momentum = (preco_final / preco_inicial - 1).dropna()\n",
"momentum.name = 'Momentum_12_1'\n",
"\n",
"df_mom = pd.DataFrame(momentum)\n",
"df_mom.index = df_mom.index.str.replace('.SA','')\n",
"df_mom = df_mom.sort_values('Momentum_12_1', ascending=False)\n",
"\n",
"print('Top 20 por Momentum 12-1:')\n",
"print(df_mom.head(20).to_string())",
]),

cell_md(["---\n## Etapa 4 — Visualização dos Vencedores e Perdedores por Momentum"]),
cell_code([
"fig, axes = plt.subplots(1, 2, figsize=(16, 6))\n",
"\n",
"# Top 15 vencedores\n",
"top15 = df_mom.head(15)\n",
"axes[0].barh(top15.index[::-1], top15['Momentum_12_1'][::-1], color='seagreen')\n",
"axes[0].set_title('Top 15 — Maior Momentum 12-1 (Candidatos)')\n",
"axes[0].set_xlabel('Retorno Acumulado (12 meses)')\n",
"axes[0].xaxis.set_major_formatter(plt.FuncFormatter(lambda x,_: f'{x:.0%}'))\n",
"\n",
"# Bottom 15 perdedores\n",
"bot15 = df_mom.tail(15)\n",
"axes[1].barh(bot15.index, bot15['Momentum_12_1'], color='tomato')\n",
"axes[1].set_title('Bottom 15 — Menor Momentum (Evitar)')\n",
"axes[1].set_xlabel('Retorno Acumulado (12 meses)')\n",
"axes[1].xaxis.set_major_formatter(plt.FuncFormatter(lambda x,_: f'{x:.0%}'))\n",
"\n",
"plt.tight_layout()\n",
"plt.show()",
]),

cell_md(["---\n## Etapa 5 — Seleção Top 12 por Momentum"]),
cell_code([
"top12_mom = df_mom.head(12).copy()\n",
"top12_tickers = [t + '.SA' for t in top12_mom.index]\n",
"\n",
"print('Top 12 ações por Momentum 12-1:')\n",
"for i, (papel, row) in enumerate(top12_mom.iterrows(), 1):\n",
"    print(f'  {i:2d}. {papel}: {row[\"Momentum_12_1\"]:+.1%}')",
]),

cell_md(["---\n## Etapa 6 — Otimização Combinatória: C(12,4) = 495 Carteiras\n\n",
"Usamos 5 anos de dados históricos (covariância de longo prazo) para a otimização de Markowitz, enquanto o Momentum **define quais candidatos entram no universo**. Esta separação é crucial: o Momentum filtra o *timing* (quando entrar), o Markowitz define os *pesos* (quanto alocar).\n"]),
cell_code([
"rf = 0.1075\n",
"precos_5a = yf.download(top12_tickers, start='2021-03-26', end='2026-03-26', progress=False)['Close']\n",
"precos_5a = precos_5a.dropna(axis=1, thresh=int(len(precos_5a)*0.8)).ffill().dropna()\n",
"tickers_v = precos_5a.columns.tolist()\n",
"\n",
"ret_d = precos_5a.pct_change().dropna()\n",
"mu = ret_d.mean() * 252\n",
"cov = ret_d.cov() * 252\n",
"\n",
"def neg_sharpe(w, mu, cov, rf):\n",
"    r = np.dot(w, mu)\n",
"    v = np.sqrt(w @ cov @ w)\n",
"    return -(r - rf) / v if v > 0 else 0\n",
"\n",
"best_s, best_c, best_w = -np.inf, None, None\n",
"for comb in combinations(tickers_v, 4):\n",
"    mu_c = mu[list(comb)].values\n",
"    cov_c = cov.loc[list(comb), list(comb)].values\n",
"    res = minimize(neg_sharpe, [0.25]*4, args=(mu_c, cov_c, rf),\n",
"                   method='SLSQP', bounds=[(0,1)]*4,\n",
"                   constraints={'type':'eq','fun':lambda w: w.sum()-1})\n",
"    if -res.fun > best_s:\n",
"        best_s = -res.fun; best_c = list(comb); best_w = res.x\n",
"\n",
"mu_f = mu[best_c].values\n",
"cov_f = cov.loc[best_c, best_c].values\n",
"ret_f, vol_f = np.dot(best_w, mu_f), np.sqrt(best_w @ cov_f @ best_w)\n",
"\n",
"print('='*55)\n",
"print('CARTEIRA ÓTIMA — MOMENTUM + MARKOWITZ')\n",
"print('='*55)\n",
"for t, w in zip(best_c, best_w):\n",
"    papel = t.replace('.SA','')\n",
"    mom_val = df_mom.loc[papel,'Momentum_12_1'] if papel in df_mom.index else float('nan')\n",
"    print(f'  {papel}: {w*100:.2f}%  (Momentum={mom_val:+.1%})')\n",
"print(f'\\n  Retorno Esperado : {ret_f*100:.2f}% a.a.')\n",
"print(f'  Volatilidade     : {vol_f*100:.2f}% a.a.')\n",
"print(f'  Índice de Sharpe : {best_s:.4f}')",
]),

cell_md(["---\n## Etapa 7 — Gráfico de Momentum Individual dos 4 Ativos"]),
cell_code([
"# Evolução do preço dos 4 ativos selecionados nos últimos 12 meses\n",
"precos_plot = yf.download(best_c, start='2025-03-01', end='2026-03-26', progress=False)['Close']\n",
"precos_norm = (precos_plot / precos_plot.iloc[0]) * 100  # Base 100\n",
"\n",
"plt.figure(figsize=(12, 6))\n",
"for col in precos_norm.columns:\n",
"    plt.plot(precos_norm.index, precos_norm[col], linewidth=2, label=col.replace('.SA',''))\n",
"plt.axhline(100, color='gray', linestyle='--', alpha=0.5, label='Base 100')\n",
"plt.title('Evolução de Preço Normalizado (Base 100) — Carteira Selecionada por Momentum')\n",
"plt.xlabel('Data')\n",
"plt.ylabel('Preço Normalizado')\n",
"plt.legend()\n",
"plt.tight_layout()\n",
"plt.show()",
]),

cell_md(["---\n## Etapa 8 — Indicadores Fundamentalistas (Exigência do Edital)"]),
cell_code([
"papeis_f = [t.replace('.SA','') for t in best_c]\n",
"df_b3['P/L'] = pd.to_numeric(df_b3['P/L'], errors='coerce')\n",
"df_b3['P/VP'] = pd.to_numeric(df_b3['P/VP'], errors='coerce')\n",
"\n",
"def pct(s):\n",
"    return pd.to_numeric(s.astype(str).str.replace('.','',regex=False)\n",
"        .str.replace(',','.',regex=False).str.replace('%','',regex=False),\n",
"        errors='coerce') / 100.0\n",
"\n",
"df_b3['ROE'] = pct(df_b3['ROE'])\n",
"df_b3['Dív.Brut/ Patrim.'] = pd.to_numeric(df_b3['Dív.Brut/ Patrim.'], errors='coerce')\n",
"\n",
"df_ind = df_b3[df_b3['Papel'].isin(papeis_f)][['Papel','ROE','P/L','P/VP','Dív.Brut/ Patrim.']].copy()\n",
"df_ind.columns = ['Ativo','ROE (Rentabilidade)','P/L (Valuation)','P/VP (Valuation)','Dív/PL (Endividamento)']\n",
"df_ind['ROE (Rentabilidade)'] = df_ind['ROE (Rentabilidade)'].map('{:.1%}'.format)\n",
"display(df_ind.reset_index(drop=True))",
]),

cell_md(["---\n## Conclusão da Estratégia Momentum\n\n",
"A Análise de Momentum resolve o principal ponto cego do Markowitz tradicional: **o timing de entrada**. ",
"Um ativo pode ter os melhores fundamentos do mundo, mas se ainda não foi reconhecido pelo mercado, comprar prematuramente significa carregar um papel em queda por meses *(value trap)*. ",
"O Momentum 12-1 filtra justamente os ativos já validados pelo mercado, concentrando a carteira em papéis com força relativa comprovada — o perfil exato para uma competição de curto prazo como esta.\n",
])
]

nb = {
 "cells": cells,
 "metadata": {
  "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
  "language_info": {"codemirror_mode": {"name": "ipython", "version": 3},
   "file_extension": ".py", "mimetype": "text/x-python", "name": "python",
   "pygments_lexer": "ipython3", "version": "3.8.0"}
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

out = r"c:\Users\User\Downloads\Competicao-de-Carteiras-2026---Analise-de-Investimento\Estrategia 3 - Analise de Momentum.ipynb"
with open(out, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print(f"Notebook gerado: {out}")
