import json

def cell_md(source): return {"cell_type":"markdown","metadata":{},"source":source}
def cell_code(source): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":source}

cells = [

cell_md([
"# Estratégia 2 — Piotroski F-Score\n",
"**Competição de Carteira de Investimentos 2026 — PPGOLD/UFPR**\n\n",
"---\n",
"## O que é o Piotroski F-Score?\n\n",
"Criado pelo professor Joseph Piotroski (University of Chicago, 2000), o F-Score é um sistema binário de pontuação que avalia a **saúde fundamentalista** de uma empresa em 9 critérios objetivos divididos em 3 eixos:\n\n",
"| Eixo | Critério | Sinal Positivo |\n",
"|---|---|---|\n",
"| **Rentabilidade** | ROA > 0 | Lucro operacional presente |\n",
"| **Rentabilidade** | FCO > 0 | Geração real de caixa |\n",
"| **Rentabilidade** | ROA crescente (vs. ano anterior) | Melhora na eficiência |\n",
"| **Rentabilidade** | FCO > Lucro Líquido (Accruals baixos) | Qualidade do lucro |\n",
"| **Alavancagem** | Dívida/Ativos diminuindo | Desalavancagem |\n",
"| **Alavancagem** | Liquidez Corrente aumentando | Melhor saúde de curto prazo |\n",
"| **Alavancagem** | Sem novas emissões de ações | Sem diluição de acionistas |\n",
"| **Eficiência** | Margem Bruta crescente | Melhora de precificação/custos |\n",
"| **Eficiência** | Giro do Ativo crescente | Melhor uso dos recursos |\n\n",
"Cada critério recebe **1 ponto (verdadeiro)** ou **0 pontos (falso)**. Score final varia de 0 a 9.\n\n",
"- **F-Score 7–9:** Empresa sólida — alta probabilidade de superar o mercado\n",
"- **F-Score 4–6:** Empresa neutra — avaliar caso a caso\n",
"- **F-Score 0–3:** Empresa fraca — evitar ou considerar short\n\n",
"## Por que o F-Score é superior ao P/L + ROE simples?\n\n",
"O P/L e ROE capturam apenas um *snapshot* pontual. O F-Score avalia **tendências e qualidade** dos indicadores — uma empresa pode ter ROE alto mas estar deteriorando rapidamente (e o F-Score captura isso).\n",
]),

cell_md(["---\n## Etapa 1 — Importação de Bibliotecas"]),
cell_code([
"import requests, io, warnings\n",
"import pandas as pd\n",
"import numpy as np\n",
"import yfinance as yf\n",
"from itertools import combinations\n",
"from scipy.optimize import minimize\n",
"import matplotlib.pyplot as plt\n",
"import matplotlib.patches as mpatches\n",
"import seaborn as sns\n",
"warnings.filterwarnings('ignore')\n",
"sns.set_style('whitegrid')\n",
"print('Bibliotecas carregadas.')",
]),

cell_md(["---\n## Etapa 2 — Coleta do Universo B3 (Fundamentus)\n",
"Extraímos todas as métricas disponíveis no Fundamentus — estas serão a base para o cálculo do F-Score adaptado.\n"]),
cell_code([
"headers = {'User-Agent': 'Mozilla/5.0'}\n",
"df_b3 = pd.read_html(io.StringIO(\n",
"    requests.get('https://www.fundamentus.com.br/resultado.php', headers=headers).text\n",
"), decimal=',', thousands='.')[0]\n",
"\n",
"def pct(s):\n",
"    return pd.to_numeric(s.astype(str).str.replace('.','',regex=False)\n",
"        .str.replace(',','.',regex=False).str.replace('%','',regex=False),\n",
"        errors='coerce') / 100.0\n",
"\n",
"for col in ['ROE','ROIC','Mrg Ebit','Mrg. Líq.','Div.Yield','Cresc. Rec.5a']:\n",
"    df_b3[col] = pct(df_b3[col])\n",
"for col in ['P/L','P/VP','EV/EBITDA','Liq.2meses','Liq. Corr.','Dív.Brut/ Patrim.']:\n",
"    df_b3[col] = pd.to_numeric(df_b3[col], errors='coerce')\n",
"\n",
"# Filtro base de liquidez\n",
"df = df_b3[df_b3['Liq.2meses'] > 5_000_000].copy().reset_index(drop=True)\n",
"print(f'Ativos líquidos disponíveis para análise: {len(df)}')",
]),

cell_md(["---\n## Etapa 3 — Cálculo do F-Score Adaptado\n\n",
"Como não temos acesso direto às demonstrações financeiras históricas via Fundamentus, usamos uma **versão adaptada do F-Score** com os dados disponíveis. ",
"Cada critério gera um ponto binário (0 ou 1). A soma totaliza o Score final de cada empresa.\n"]),
cell_code([
"fscore = pd.DataFrame({'Papel': df['Papel']})\n",
"\n",
"# EIXO 1 — RENTABILIDADE (4 critérios)\n",
"# F1: ROE > 0 (proxy para ROA positivo)\n",
"fscore['F1_ROE_pos']       = (df['ROE'] > 0).astype(int)\n",
"# F2: Margem Líquida > 0 (proxy para FCO > 0)\n",
"fscore['F2_Mrg_pos']       = (df['Mrg. Líq.'] > 0).astype(int)\n",
"# F3: ROIC > ROE anterior — usamos ROIC vs ROE como proxy de melhora\n",
"fscore['F3_ROIC_gt_ROE']   = (df['ROIC'] > df['ROE']).astype(int)\n",
"# F4: Margem EBIT > Margem Líquida (Accruals baixos = FCO saudável)\n",
"fscore['F4_low_accruals']  = (df['Mrg Ebit'] > df['Mrg. Líq.']).astype(int)\n",
"\n",
"# EIXO 2 — ALAVANCAGEM / LIQUIDEZ (3 critérios)\n",
"# F5: Dívida/PL < 1 (alavancagem razoável)\n",
"fscore['F5_divida_ok']     = (df['Dív.Brut/ Patrim.'] < 1.0).astype(int)\n",
"# F6: Liquidez Corrente > 1 (saúde de curto prazo)\n",
"fscore['F6_liq_corr']      = (df['Liq. Corr.'] > 1.0).astype(int)\n",
"# F7: Crescimento de receita positivo (proxy para sem diluição)\n",
"fscore['F7_cresc_rec']     = (df['Cresc. Rec.5a'] > 0).astype(int)\n",
"\n",
"# EIXO 3 — EFICIÊNCIA OPERACIONAL (2 critérios)\n",
"# F8: Margem EBIT positiva (eficiência operacional)\n",
"fscore['F8_mrg_ebit_pos']  = (df['Mrg Ebit'] > 0).astype(int)\n",
"# F9: PSR < P/Ativo (proxy de giro do ativo saudável)\n",
"fscore['F9_efic_ativo']    = (df['ROIC'] > 0.10).astype(int)  # ROIC > 10% = bom uso dos ativos\n",
"\n",
"fscore['F_SCORE'] = fscore.iloc[:, 1:].sum(axis=1)\n",
"\n",
"# Merge com dados originais\n",
"df_result = df.merge(fscore, on='Papel')\n",
"print(f'F-Score calculado para {len(df_result)} empresas.')\n",
"print(f\"\\nDistribuição dos scores:\")\n",
"print(df_result['F_SCORE'].value_counts().sort_index())",
]),

cell_md(["---\n## Etapa 4 — Visualização da Distribuição do F-Score"]),
cell_code([
"fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
"\n",
"# Histograma da distribuição\n",
"df_result['F_SCORE'].plot(kind='hist', bins=10, ax=axes[0], color='steelblue', edgecolor='white')\n",
"axes[0].axvline(7, color='red', linestyle='--', label='Corte F-Score ≥ 7')\n",
"axes[0].set_title('Distribuição do Piotroski F-Score — B3')\n",
"axes[0].set_xlabel('F-Score (0–9)')\n",
"axes[0].legend()\n",
"\n",
"# Top 15 empresas com maior F-Score\n",
"top15 = df_result.nlargest(15, 'F_SCORE')\n",
"colors = ['green' if s >= 7 else 'orange' for s in top15['F_SCORE']]\n",
"axes[1].barh(top15['Papel'], top15['F_SCORE'], color=colors)\n",
"axes[1].axvline(7, color='red', linestyle='--', label='Corte ≥ 7')\n",
"axes[1].set_title('Top 15 Ativos por F-Score')\n",
"axes[1].set_xlabel('F-Score')\n",
"axes[1].legend()\n",
"\n",
"plt.tight_layout()\n",
"plt.show()",
]),

cell_md(["---\n## Etapa 5 — Seleção da Elite: F-Score ≥ 7 + Alta Liquidez"]),
cell_code([
"elite = df_result[(df_result['F_SCORE'] >= 7) & (df_result['Liq.2meses'] > 5_000_000)].copy()\n",
"elite = elite.sort_values('F_SCORE', ascending=False)\n",
"\n",
"print(f'Empresas com F-Score ≥ 7 e alta liquidez: {len(elite)}')\n",
"display(elite[['Papel','F_SCORE','ROE','Mrg. Líq.','Liq. Corr.','Dív.Brut/ Patrim.','Liq.2meses']]\n",
"        .head(12).reset_index(drop=True))\n",
"\n",
"top12 = elite.head(12)\n",
"tickers_top = [t + '.SA' for t in top12['Papel'].tolist()]",
]),

cell_md(["---\n## Etapa 6 — Otimização Combinatória Markowitz: C(12,4) = 495 Carteiras"]),
cell_code([
"rf = 0.1075\n",
"precos = yf.download(tickers_top, start='2021-03-26', end='2026-03-26', progress=False)['Close']\n",
"precos = precos.dropna(axis=1, thresh=int(len(precos)*0.8)).ffill().dropna()\n",
"tickers_validos = precos.columns.tolist()\n",
"\n",
"ret_d = precos.pct_change().dropna()\n",
"mu = ret_d.mean() * 252\n",
"cov = ret_d.cov() * 252\n",
"\n",
"def neg_sharpe(w, mu, cov, rf):\n",
"    r = np.dot(w, mu)\n",
"    v = np.sqrt(w @ cov @ w)\n",
"    return -(r - rf) / v if v > 0 else 0\n",
"\n",
"best_sharpe, best_comb, best_w = -np.inf, None, None\n",
"\n",
"for comb in combinations(tickers_validos, 4):\n",
"    mu_c = mu[list(comb)].values\n",
"    cov_c = cov.loc[list(comb), list(comb)].values\n",
"    res = minimize(neg_sharpe, [0.25]*4, args=(mu_c, cov_c, rf),\n",
"                   method='SLSQP', bounds=[(0,1)]*4,\n",
"                   constraints={'type':'eq','fun':lambda w: w.sum()-1})\n",
"    if -res.fun > best_sharpe:\n",
"        best_sharpe = -res.fun\n",
"        best_comb = list(comb)\n",
"        best_w = res.x\n",
"\n",
"mu_f = mu[best_comb].values\n",
"cov_f = cov.loc[best_comb, best_comb].values\n",
"ret_f = np.dot(best_w, mu_f)\n",
"vol_f = np.sqrt(best_w @ cov_f @ best_w)\n",
"\n",
"print('='*55)\n",
"print('CARTEIRA ÓTIMA — PIOTROSKI F-SCORE + MARKOWITZ')\n",
"print('='*55)\n",
"for t, w in zip(best_comb, best_w):\n",
"    fscore_val = df_result[df_result['Papel']==t.replace('.SA','')]['F_SCORE'].values\n",
"    fscore_str = f'(F-Score={int(fscore_val[0])})' if len(fscore_val) > 0 else ''\n",
"    print(f'  {t.replace(\".SA\",\"\")}: {w*100:.2f}% {fscore_str}')\n",
"print(f'\\n  Retorno Esperado : {ret_f*100:.2f}% a.a.')\n",
"print(f'  Volatilidade     : {vol_f*100:.2f}% a.a.')\n",
"print(f'  Índice de Sharpe : {best_sharpe:.4f}')",
]),

cell_md(["---\n## Etapa 7 — Visualização: Fronteira Eficiente"]),
cell_code([
"n_sim = 10000\n",
"rets, vols, sharpes = [], [], []\n",
"for _ in range(n_sim):\n",
"    w = np.random.dirichlet(np.ones(4))\n",
"    r = np.dot(w, mu_f)\n",
"    v = np.sqrt(w @ cov_f @ w)\n",
"    rets.append(r); vols.append(v); sharpes.append((r-rf)/v)\n",
"\n",
"plt.figure(figsize=(10,6))\n",
"sc = plt.scatter(vols, rets, c=sharpes, cmap='plasma', s=8, alpha=0.4)\n",
"plt.colorbar(sc, label='Índice de Sharpe')\n",
"plt.scatter(vol_f, ret_f, marker='*', color='red', s=300, zorder=5,\n",
"            label=f'Portfólio Ótimo (Sharpe={best_sharpe:.2f})')\n",
"plt.axhline(rf, color='gray', linestyle='--', label=f'CDI ({rf*100:.1f}%)')\n",
"plt.xlabel('Risco Anualizado (Volatilidade)')\n",
"plt.ylabel('Retorno Anualizado')\n",
"plt.title('Fronteira Eficiente — Estratégia Piotroski F-Score')\n",
"plt.legend()\n",
"plt.tight_layout()\n",
"plt.show()",
]),

cell_md(["---\n## Etapa 8 — Indicadores Exigidos pelo Edital"]),
cell_code([
"papeis_f = [t.replace('.SA','') for t in best_comb]\n",
"colunas  = ['Papel','F_SCORE','ROE','P/L','P/VP','Dív.Brut/ Patrim.']\n",
"df_ind = df_result[df_result['Papel'].isin(papeis_f)][colunas].copy()\n",
"df_ind.columns = ['Ativo','F-Score','ROE (Rentabilidade)','P/L (Valuation)','P/VP (Valuation)','Dív/PL (Endividamento)']\n",
"df_ind['ROE (Rentabilidade)'] = df_ind['ROE (Rentabilidade)'].map('{:.1%}'.format)\n",
"display(df_ind.reset_index(drop=True))\n",
"print('\\nIndicadores prontos para o Relatório Técnico da Competição.')",
]),

cell_md(["---\n## Conclusão da Estratégia Piotroski F-Score\n\n",
"O Piotroski F-Score representa um avanço significativo em relação ao uso isolado de P/L e ROE, pois avalia a **qualidade e a trajetória** dos fundamentos em 3 eixos distintos — exatamente os 3 eixos exigidos pelo edital da competição. ",
"Ao combinar O F-Score ≥ 7 com a otimização quantitativa de Markowitz, garantimos que as empresas selecionadas não são apenas baratas ou rentáveis, mas **saudáveis estruturalmente**, com tendência de melhora — o perfil ideal para uma carteira que visa superar o CDI com retorno ajustado ao risco.\n",
])
]

nb = {
 "cells": cells,
 "metadata": {
  "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
  "language_info": {"codemirror_mode": {"name": "ipython", "version": 3},
   "file_extension": ".py", "mimetype": "text/x-python", "name": "python",
   "pygments_lexer": "ipython3", "version": "3.8.0"}
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

out = r"c:\Users\User\Downloads\Competicao-de-Carteiras-2026---Analise-de-Investimento\Estrategia 2 - PIOTROSKI F-SCORE.ipynb"
with open(out, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print(f"Notebook gerado: {out}")
